export const illustrations = {
  approvedPayment: '/images/illustrations/approvedPayment.svg',
  buildACommunity: '/images/illustrations/buildACommunity.svg',
  calendar: '/images/illustrations/calendar.svg',
  chatbot: '/images/illustrations/chatbot.svg',
  chatSupport: '/images/illustrations/chatSupport.svg',
  codeCollaboration: '/images/illustrations/codeCollaboration.svg',
  coder: '/images/illustrations/coder.svg',
  codeReview: '/images/illustrations/codeReview.svg',
  contactUs: '/images/illustrations/contactUs.svg',
  customerSupport247: '/images/illustrations/customerSupport247.svg',
  customerSupportFeedback: '/images/illustrations/customerSupportFeedback.svg',
  dataReport: '/images/illustrations/dataReport.svg',
  developer: '/images/illustrations/developer.svg',
  emptyInbox: '/images/illustrations/emptyInbox.svg',
  emptyStateInbox: '/images/illustrations/emptyStateInbox.svg',
  error404: '/images/illustrations/error404.svg',
  fillAForm: '/images/illustrations/fillAForm.svg',
  group: '/images/illustrations/group.svg',
  matchNotFound: '/images/illustrations/matchNotFound.svg',
  messaging: '/images/illustrations/messaging.svg',
  newsletter: '/images/illustrations/newsletter.svg',
  noInternet: '/images/illustrations/noInternet.svg',
  notes: '/images/illustrations/notes.svg',
  officeParty: '/images/illustrations/officeParty.svg',
  onlineBanking: '/images/illustrations/onlineBanking.svg',
  onlineReviews: '/images/illustrations/onlineReviews.svg',
  pageNotFound: '/images/illustrations/pageNotFound.svg',
  readingOnCouch: '/images/illustrations/readingOnCouch.svg',
  referAFriend: '/images/illustrations/referAFriend.svg',
  resume: '/images/illustrations/resume.svg',
  saveTime: '/images/illustrations/saveTime.svg',
  searching: '/images/illustrations/searching.svg',
  secureLogin: '/images/illustrations/secureLogin.svg',
  stayAtHome: '/images/illustrations/stayAtHome.svg',
  success: '/images/illustrations/success.svg',
  supportQuestions: '/images/illustrations/supportQuestions.svg',
  targetAchieved: '/images/illustrations/targetAchieved.svg',
  todoList: '/images/illustrations/todoList.svg',
  videoCall: '/images/illustrations/videoCall.svg',
  visualData: '/images/illustrations/visualData.svg',
  welcome: '/images/illustrations/welcome.svg',
  whiteboard: '/images/illustrations/whiteboard.svg',
}

const illustrationNames = Object.keys(illustrations) as Array<keyof typeof illustrations>;
export type IllustrationType = typeof illustrationNames[number];